services:
  # db:
  #   image: postgres:16-alpine # Use a specific version of the official image from Docker Hub
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./data/db:/var/lib/postgresql/danisme/data # Persist data to a local volume
  #   networks:
  #     - app-network

  backend:
    build:
      context: ./backend # Path to your backend's Dockerfile
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "5000:5000" # Or whatever port your backend uses
    # depends_on:
    #   - db # Ensure the database starts first
    environment:
      - NODE_ENV=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000" # Map host port 3000 to container port 80
    depends_on:
      - backend # Depending on your setup, might depend on backend
